name: Deploy to GCP Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Google Cloud SDK
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: Set up Cloud SDK
        uses: "google-github-actions/setup-gcloud@v3"

      - name: Configure Docker for GCP
        run: gcloud auth configure-docker

      - name: use gcloud
        run: "gcloud info"

      # - name: Build and push Docker image
      #   run: |
      #     IMAGE=gcr.io/${{ secrets.GCP_PROJECT_ID }}/stand-metrics:${{ github.sha }}
      #     docker build -t $IMAGE .
      #     docker push $IMAGE

      # - name: Deploy to Cloud Run
      #   run: |
      #     IMAGE=gcr.io/${{ secrets.GCP_PROJECT_ID }}/stand-metrics:${{ github.sha }}
      #     gcloud run deploy stand-metrics \
      #       --image $IMAGE \
      #       --region ${{ secrets.GCP_REGION }} \
      #       --platform managed \
      #       --allow-unauthenticated
