name: Lint & Test

on:
  push:
    branches: ["cleanup"]
  pull_request:
    branches: ["main"]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3

  build:
    runs-on: ubuntu-latest
    needs: ruff
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.11"]
    steps:
      - name: Update Apt Cache
        run: sudo apt-get update -y
      - name: Install Apt Dependencies
        run: sudo apt-get install libcurl4-openssl-dev libssl-dev gcc gdal-bin libgdal-dev r-base-core -y
      - uses: actions/checkout@v4
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
      - name: Run Tests
        run: |
          uv run pytest .
